CREATE TABLE public.ArtigoInformativo (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo character varying NOT NULL,
    corpo text NOT NULL,
    autor character varying,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    url_artigo text,
    url_imagem text,
    CONSTRAINT ArtigoInformativo_pkey PRIMARY KEY (id)
);

CREATE TABLE public.CategoriaMaterial (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome character varying NOT NULL,
    descricao text,
    data_criacao timestamp with time zone DEFAULT now(),
    CONSTRAINT CategoriaMaterial_pkey PRIMARY KEY (id)
);

CREATE TABLE public.DadosEstatisticosTEA (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conteudo text NOT NULL,
    nome character varying NOT NULL,
    fonte character varying,
    descricao text,
    data_criacao timestamp with time zone DEFAULT now(),
    CONSTRAINT DadosEstatisticosTEA_pkey PRIMARY KEY (id)
);

CREATE TABLE public.NivelSuporteTEA (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome character varying NOT NULL,
    descricao text,
    data_criacao timestamp with time zone DEFAULT now(),
    CONSTRAINT NivelSuporteTEA_pkey PRIMARY KEY (id)
);

CREATE TABLE public.TipoServico (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying NOT NULL,
    descricao text,
    data_criacao timestamp with time zone DEFAULT now(),
    CONSTRAINT TipoServico_pkey PRIMARY KEY (id)
);

CREATE TABLE public.TEA_escolarizacao_por_estado (
    localidade text,
    ano bigint,
    sexo text,
    faixa_idade text,
    tipo_deficiencia text,
    taxa_escolarizacao double precision
);

CREATE TABLE public.TEA_nivel_por_estado (
    id text NOT NULL,
    local text,
    dificuldades text,
    absolute bigint,
    relative double precision,
    CONSTRAINT TEA_nivel_por_estado_pkey PRIMARY KEY (id)
);

CREATE TABLE public.Responsavel (
    id uuid NOT NULL,
    nome character varying NOT NULL,
    email character varying NOT NULL UNIQUE,
    senha_hash character varying,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    CONSTRAINT Responsavel_pkey PRIMARY KEY (id),
    CONSTRAINT Responsavel_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE public.Dependente (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome character varying NOT NULL,
    responsavel_id uuid NOT NULL,
    nivel_suporte_tea_id integer,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    CONSTRAINT Dependente_pkey PRIMARY KEY (id),
    CONSTRAINT Dependente_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.Responsavel(id),
    CONSTRAINT Dependente_nivel_suporte_tea_id_fkey FOREIGN KEY (nivel_suporte_tea_id) REFERENCES public.NivelSuporteTEA(id)
);

CREATE TABLE public.DepoimentoResponsavel (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto text NOT NULL,
    aprovado boolean DEFAULT false,
    responsavel_id uuid NOT NULL,
    categoria_id integer,
    data_criacao timestamp with time zone DEFAULT now(),
    CONSTRAINT DepoimentoResponsavel_pkey PRIMARY KEY (id),
    CONSTRAINT DepoimentoResponsavel_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.Responsavel(id),
    CONSTRAINT DepoimentoResponsavel_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.CategoriaMaterial(id)
);

CREATE TABLE public.MaterialDeApoio (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo character varying NOT NULL,
    corpo text,
    categoria_id integer,
    nivel_suporte_tea_id integer,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    url_icone text,
    url_fonte text,
    CONSTRAINT MaterialDeApoio_pkey PRIMARY KEY (id),
    CONSTRAINT MaterialDeApoio_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.CategoriaMaterial(id),
    CONSTRAINT MaterialDeApoio_nivel_suporte_tea_id_fkey FOREIGN KEY (nivel_suporte_tea_id) REFERENCES public.NivelSuporteTEA(id)
);

CREATE TABLE public.MaterialFavorito (
    responsavel_id uuid NOT NULL,
    material_id integer NOT NULL,
    dependente_id integer NOT NULL,
    data_favoritado timestamp with time zone DEFAULT now(),
    CONSTRAINT MaterialFavorito_pkey PRIMARY KEY (responsavel_id, material_id, dependente_id),
    CONSTRAINT MaterialFavorito_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.Responsavel(id),
    CONSTRAINT MaterialFavorito_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.MaterialDeApoio(id),
    CONSTRAINT MaterialFavorito_dependente_id_fkey FOREIGN KEY (dependente_id) REFERENCES public.Dependente(id)
);

CREATE TABLE public.ServicoLocal (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying NOT NULL,
    endereco character varying,
    tipo_servico_id integer,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    url_servico text,
    CONSTRAINT ServicoLocal_pkey PRIMARY KEY (id),
    CONSTRAINT ServicoLocal_tipo_servico_id_fkey FOREIGN KEY (tipo_servico_id) REFERENCES public.TipoServico(id)
);